---
title: "R Notebook"
---

# Metadata extraction
For what_is building.
```{r}
metadf = read.csv("../data/v300/Metadata_Agrimonia_v_3_0_0.csv",sep=";",head=T)
head(metadf)
dim(metadf)
colnames(metadf)
for (i in 1:54){
	if (metadf[i,2]!=""){
		cat(paste0('what_is[["',metadf[i,2],'"]] = "',metadf[i,"DESCRIPTION"]),"\\n["
			,metadf[i,4],']"\n')
	}
}
```


# Stations split
```{r}
load("../data/v300/df_agri.Rdata")
df_agri$Time <- as.Date(df_agri$Time, "%Y-%m-%d")
# df_agri$Time <- format(df_agri$Time, format = "%d/%m/%Y")
# df_agri$Time <- as.Date(df_agri$Time, format = "%d/%m/%Y")
df = df_agri
head(df)
library(hash)
df_stat = hash()
stations = unique(df$IDStations)
print(stations)
```

# data saving
```{r}
for (st in stations){
	df_stat[[st]] = df[which(df$IDStations == st),]
	dim(df_stat[[st]]) # == 2192) # make sure each df_stat has all his 2192 obs
}
# example
df_stat[["1264"]]
save(df_stat,file="../data/v300/df_stat.Rdata")
```

# week division
```{r}
library(dplyr)
library(lubridate)


add_week_column <- function(data) {
  data <- data %>%
    mutate(Time = ymd(Time),  # Convert the date column to a date object
           week = week(Time))  # Extract the week number
  
  return(data)
}

example = df_stat[["1264"]]

# Add the week column
example <- add_week_column(example)
example=example %>% relocate(week, .after = Time)
head(example)
range(example$week)
```

