---
title: "R Notebook"
output: html_document
---

```{r}
library(GGally) #for ggcorr
library(ggplot2)
library(dplyr)
```

# Dataset comparison

```{r}
df_agri = read.csv("../data/Agrimonia_Dataset_v_3_0_0.csv")
AGC_Dataset = read.csv("../data/AGC_Dataset_v_3_0_0.csv")
save(AGC_Dataset,file="data_agc_lomb.Rdata")
save(df_agri,file="df_agri.Rdata")
```

It seems that the agc one is less complete, even if it wheights more memory (as it has more lines).
So for now df will be df_agri.

```{r}
print("df agri ##############")
colnames(df_agri)
dim(df_agri)

print("df agc ##############")
colnames(AGC_Dataset)
dim(AGC_Dataset)

df = df_agri
```

```{r}
head(AGC_Dataset)
head(df_agri)
AGC_Dataset$Time[length(AGC_Dataset$Time)]
df_agri$Time[length(df_agri$Time)]
```


```{r}
```


# First plots
```{r}
head(df)

length(unique(df$Latitude)) # we have 141 stations
length(unique(df$Time)) # which recorded data for 2192 days
dim(df)[1]/2192 == 141
```

We have 2192 days: between 1st January 2016 and 31st December 2021.
Plot the trend of PM10 measurements for the first FIRST_STAT stations

```{r}
fun_colori = function(len=2, seed=33){
	hcols_ = hcl.pals()
	col.ramp_ = hcl.colors(len,palette=hcols_[seed%%115+1])
	return(col.ramp_)
}
colori_fun = colorami = colora = fun_colori
```


```{r}
FIRST_STAT = 10
for (stat in unique(df$IDStations)[1:FIRST_STAT]) {
	# print(stat)
	# print(length(df[which(df$IDStations==stat),"AQ_pm10"]))
	# print(max(na.omit(df[which(df$IDStations==stat),"AQ_pm10"])))
	y = df[which(df$IDStations==stat),"AQ_pm10"]
	y = na.omit(y)
	if (length(y)>10){
		plot(1:length(y),y,type="l")
		title(paste("station",stat))
		abline(v=0   ,col="red"); text(20     ,max(y),"16",col="red",cex=0.5)
		abline(v=366 ,col="red"); text(366+20 ,max(y),"17",col="red",cex=0.5)
		abline(v=731 ,col="red"); text(731+20 ,max(y),"18",col="red",cex=0.5)
		abline(v=1096,col="red"); text(1096+20,max(y),"19",col="red",cex=0.5)
		abline(v=1461,col="red"); text(1461+20,max(y),"20",col="red",cex=0.5)
		abline(v=1827,col="red"); text(1827+20,max(y),"21",col="red",cex=0.5)
		
		#          16  17 18  19  20  21
		days = c(366,365,365,365,366,365)
		cdays = c(0,cumsum(days))
		cols = colora(length(days),2)
		plot(1:days[1],y[cdays[1]+1:days[1]],type="l", col=cols[1])
		lines(1:days[2],y[cdays[2]+1:days[2]],type="l",col=cols[2])
		lines(1:days[3],y[cdays[3]+1:days[3]],type="l",col=cols[3])
		lines(1:days[4],y[cdays[4]+1:days[4]],type="l",col=cols[4])
		lines(1:days[5],y[cdays[5]+1:days[5]],type="l",col=cols[5])
		lines(1:days[6],y[cdays[6]+1:days[6]],type="l",col=cols[6])
	}
	# plot(1:2192,df[which(df$IDStations==stat),"AQ_pm10"])
}
```


```{r}
summary(df)
```




```{r}
AQ_cols = colnames(df)[grep("AQ_",colnames(df))]
WE_cols = colnames(df)[grep("WE_",colnames(df))]
EM_cols = colnames(df)[grep("EM_",colnames(df))]
LI_cols = colnames(df)[grep("LI_",colnames(df))]
LA_cols = colnames(df)[grep("LA_",colnames(df))]

AQ_idxs = grep("AQ_",colnames(df))
WE_idxs = grep("WE_",colnames(df))
EM_idxs = grep("EM_",colnames(df))
LI_idxs = grep("LI_",colnames(df))
LA_idxs = grep("LA_",colnames(df))

```


```{r}
ggcorr(select_if(df[,AQ_idxs],is.numeric),label=TRUE,label_size = 3)
ggcorr(select_if(df[,WE_idxs],is.numeric),label=TRUE,label_size = 3)
ggcorr(select_if(df[,EM_idxs],is.numeric),label=TRUE,label_size = 3)
ggcorr(select_if(df[,LI_idxs],is.numeric),label=TRUE,label_size = 3)
ggcorr(select_if(df[,LA_idxs],is.numeric),label=TRUE,label_size = 3)
```

