---
title: "R Notebook"
output: html_notebook
---
```{r}
source("include.R") 
```

```{r}
library(CARBayesST)
```
```{r}
head(df_wsc)
```
# ORDER BY TIME
The values in each column of these matrices should be ordered so that the first K data points are the set of all K spatial locations at time1, the next K are the set of spatial locations for time 2 and so on.
```{r}
ordered_by_time <- df_wsc[order(df_wsc$Time), ]
head(ordered_by_time)
```
# neighbourhood matrix
```{r}
library(sp)
library(proxy)
spatial_coord = df_wsc[df_wsc$Time=="2018-01-01",c("IDStations","Latitude","Longitude")]
head(spatial_coord)

coordinates(spatial_coord) <- c("Longitude", "Latitude")

# Calculate the pairwise Euclidean distance matrix
dist_matrix <- proxy::dist(coordinates(spatial_coord), method = "Euclidean")
dim(dist_matrix)

```

```{r}
formula = as.formula("AQ_pm10~.")
```

```{r}
mod<-MVST.CARar(formula= formula,
		   family = "gaussian",
		   data=ordered_by_time,
		   W= dist_matrix,
		   burnin = 10,
		   n.sample = 2,
		   thin=1, 
		   n.chains=1, 
		   n.cores=1,
		   prior.mean.beta=NULL,
		   prior.var.beta=NULL,
		   prior.nu2=NULL, 
		   prior.Sigma.df=NULL,
		   prior.Sigma.scale=NULL,
		   AR=1, #1 or 2
		   rho.S=NULL,
		   rho.T=NULL, 
		   MALA=TRUE,
		   verbose=TRUE)
```



