---
title: "R Notebook"
output: html_notebook
---


```{r,warning = FALSE}
library(drpm)
library(salso)

# preparation
source("include.R") # for having df_agri
source("plot functions/plotter.R")

sites = data.frame(
	longitude = unique(df_weekly$Longitude), 
	latitude = unique(df_weekly$Latitude))

```


# create a pm10 table (station x time)


```{r}
stations = unique(df_weekly$IDStations)
y=data.frame()

for(st in stations){
  y_we_pm10=cbind(as.data.frame(st),t(df_weekly[which(df_weekly$IDStations==st),7]))
  y=rbind(y,y_we_pm10)
}

rownames(y) = NULL
colnames(y)<- c("id",paste0("w", 1:53))
y
```


# plot
```{r}
yred=y[,2:54]
cols = colora(size(yred)[1],56,0)
for(i in 1:size(yred)[1]){
   if(i==1){
     plot(1:size(yred)[2],yred[i,],col=cols[i],ylim=extrema(yred),type='l',xlab='weeks',ylab='pm10')
 	  } 
	  else{
		  lines(1:size(yred)[2],yred[i,],col=cols[i])
	  }
}
```
```{r}
cols = colora(105,56,show=F)

trendYearStation_week <- function(file_name){

	data_from_to = df_weekly
	len_time = 54
	

	chosen_variable = (data_from_to[,chosen_variable_name])
	
	
	# Crea il grafico ggplot
	station_trend <- ggplot(data_from_to,aes(x = week, 
												 y = AQ_pm10,
												 group=IDStations, 
												 color = as.factor(IDStations))) +
		
		geom_line(show.legend = FALSE) +
		labs(x = "Stations", y = chosen_variable_name, title = "Year: 2018 all stations") +
		ylim(range(na.omit(chosen_variable))) +
		scale_color_manual(values = cols) +
		theme_bw()+
		theme(panel.grid = element_blank()) +
		guides(color = guide_legend())+
		labs(x="week")
	
	len_time = (len_time%/%5)

	return(trend_animator(file_name,station_trend, data_from_to$week,len_time))
}
trendYearStation_week("None")
```


# fit
```{r}
drpm1 <- drpm_fit(y[,2:20], 
         M=1,
         initial_partition = NULL,
         starting_alpha = 0.5,
         unit_specific_alpha = FALSE,
         time_specific_alpha = TRUE,
         alpha_0=FALSE,
         eta1_0=FALSE,
         phi1_0=FALSE,
         modelPriors=c(40,100^2,1,1,1,1),
         alphaPriors=rbind(c(1,1)),
         simpleModel = 0,
         theta_tau2 = c(0, 2),
         SpatialCohesion=4,
         cParms=c(0, 1, 2, 1),
         mh=c(0.5, 1, 0.1, 0.1, 0.1),
         verbose=TRUE,
         draws=1100,burn=100,thin=1)
```
```{r}
size(drpm1$Si)
# questa cos ha le simulazioni dei cluster assegnati
# ha dimensione 53 righe, 105 colonne, 1000 volte, perché
# - per ognuna delle 1000 iterazioni delle MCMC
# - dà i cluster assegnati dalla simulazione per le stazioni in quella simulazione

```

# study cluster division
check morale di cosa intende quella divisione.



```{r}
plot(summary(salso_out)$dendrogram) # boh
```



Sembra ci siano molti cluster piccoli, quindi forse occorre capire le prior/i parametri di drpm_fit per aggiustare questo fenomeno.

```{r,warning=FALSE}
time_span = 1:10
for(time in time_span){

	salso_out <- salso(t(drpm1$Si[time,,]),loss="binder")
		
	n_clusters = max(salso_out)
	ycurrent = y[,paste0("w",time)]
	ycurrent = log(ycurrent)
	cat(crayon::cyan("Time",time,"\n"))
	for (cl in 1:n_clusters){

		cat("Cluster",cl,"- size",length(ycurrent[which(salso_out==cl)]),
			"- mean",mean(ycurrent[which(salso_out==cl)]),"\n")

	}

	clust_vals = salso_out[1:105]
	df_temp = data.frame(clust_vals=clust_vals,ycurrent=ycurrent)

	# per ora stiamo lavorando sui valori del dataset,
	# ma dobbiamo ricordarci che li dobbiamo log-trasformare in realtà
	
	p = ggplot(df_temp, aes(ycurrent, fill = factor(clust_vals))) +

		scale_fill_manual(values = colora(n_clusters,77,0),name="Cluster")+
		geom_density(alpha = 0.4)+
		ggtitle(paste("Time",time))+
		theme_classic()
	print(p)

} # end for(time in eccc)
```



# simple evolution plot
## dataframe for clusters
```{r,warning=FALSE}
df_cluster = data.frame(Longitude=c(),Latitude=c(),values=c(),clusters=c(),Time=c())
for(time in time_span){

	salso_out <- salso(t(drpm1$Si[time,,]),loss="binder")
	
	df_temp = data.frame(
		Longitude = sites$longitude,
		Latitude = sites$latitude,
		clusters = salso_out[1:105]
	)
	df_temp$Time = rep(time,dim(df_temp)[1])
	df_cluster = rbind(df_cluster,df_temp)
}
```


## Plot for time 1
```{r}
df_cluster_cut = df_cluster[df_cluster$Time==time,]
p  <-  DefaultPlot()+
	geom_point(data = df_cluster_cut, aes(x = Longitude, y = Latitude, color = factor(clusters)), size = 3)+
	labs(title = "Cluster map")+
		guides(color = guide_legend(title = "Clusters"))

p
```

## Save png(s) for animation
```{r}
for( time in time_span){
	df_cluster_cut = df_cluster[df_cluster$Time==time,]
	
	p  <-  DefaultPlot()+
		geom_point(data = df_cluster_cut, aes(x = Longitude, y = Latitude, 
											  color = factor(clusters)), size = 3)+
		labs(title = "Cluster map")+
		guides(color = guide_legend(title = "Clusters"))
	
	ggsave(
	  paste0("cluster_plots/cluster_time-",time,".png"),
	  plot = p
	)
}

```









