---
title: "R Notebook"
output: html_document
---

```{r}
library(GGally) #for ggcorr
library(ggplot2)
library(dplyr)
```

# Dataset comparison

```{r}
df_agri = read.csv("../data/v300/Agrimonia_Dataset_v_3_0_0.csv")
df_agc = read.csv("../data/v300/AGC_Dataset_v_3_0_0.csv")
```

It seems that the agc one is less complete, even if it wheights more memory (as it has more lines).
So for now df will be df_agri.

```{r}
print("df agri ##############")
colnames(df_agri)
dim(df_agri)

print("df agc ##############")
colnames(df_agc)
dim(df_agc)

df = df_agri
```

# First plots
```{r}
head(df)

length(unique(df$Latitude)) # we have 141 stations
length(unique(df$Time)) # which recorded data for 2192 days
dim(df)[1]/2192 == 141
```

Plot the trend of PM10 measurements for the first FIRST_STAT stations
```{r}
FIRST_STAT = 10
for (stat in unique(df$IDStations)[1:FIRST_STAT]) {
	# print(stat)
	# print(length(df[which(df$IDStations==stat),"AQ_pm10"]))
	# print(max(na.omit(df[which(df$IDStations==stat),"AQ_pm10"])))
	y = df[which(df$IDStations==stat),"AQ_pm10"]
	y = na.omit(y)
	if (length(y)>10){
		plot(1:length(y),y,type="l")
		title(paste("station",stat))
	}
	# plot(1:2192,df[which(df$IDStations==stat),"AQ_pm10"])
}
```



```{r}
AQ_cols = colnames(df)[grep("AQ_",colnames(df))]
WE_cols = colnames(df)[grep("WE_",colnames(df))]
EM_cols = colnames(df)[grep("EM_",colnames(df))]
LI_cols = colnames(df)[grep("LI_",colnames(df))]
LA_cols = colnames(df)[grep("LA_",colnames(df))]

AQ_idxs = grep("AQ_",colnames(df))
WE_idxs = grep("WE_",colnames(df))
EM_idxs = grep("EM_",colnames(df))
LI_idxs = grep("LI_",colnames(df))
LA_idxs = grep("LA_",colnames(df))

```


```{r}
ggcorr(select_if(df[,AQ_idxs],is.numeric),label=TRUE,label_size = 3)
ggcorr(select_if(df[,WE_idxs],is.numeric),label=TRUE,label_size = 3)
ggcorr(select_if(df[,EM_idxs],is.numeric),label=TRUE,label_size = 3)
ggcorr(select_if(df[,LI_idxs],is.numeric),label=TRUE,label_size = 3)
ggcorr(select_if(df[,LA_idxs],is.numeric),label=TRUE,label_size = 3)
```

