---
title: "R Notebook"
output: html_notebook
---

```{r}
source("include.R")
```


# ppmSuite
```{r}
install.packages("ppmSuite")
```

test: load a dataset that there is in the package
```{r}
library(ppmSuite)
head(ppmSuite::bear)
```

# DRPM
```{r}
library(devtools)
devtools::install_github("https://github.com/gpage2990/drpm.git")
```

test 
```{r}
library(drpm)
sites = data.frame(
	longitude = unique(df_agri$Longitude), 
	latitude = unique(df_agri$Latitude))

drpm_fit(y=matrix(data=rnorm(105*10),nrow = 105,ncol = 10), # random data
         s_coords=as.matrix(sites),
         M=1,
         initial_partition = NULL,
         starting_alpha = 0.5,
         unit_specific_alpha = FALSE,
         time_specific_alpha = FALSE,
         alpha_0=FALSE,
         eta1_0=FALSE,
         phi1_0=FALSE,
         modelPriors=c(0,100^2,1,1,1,1),
         alphaPriors=rbind(c(1,1)),
         simpleModel = 0,
         theta_tau2 = c(0, 2),
         SpatialCohesion=4,
         cParms=c(0, 1, 2, 1),
         mh=c(0.5, 1, 0.1, 0.1, 0.1),
         verbose=TRUE,
         draws=1100,burn=100,thin=1)
```

