---
title: "R Notebook"
output: html_notebook
---
install.packages("ppmSuite")

```{r}
library(ppmSuite)
```

# Test ppmSuite installation
```{r}
head(ppmSuite::bear)
# it's a dataset of ppmSuite
# If there is output it means that it works, the package is correctly installed
```





https://www.tandfonline.com/doi/suppl/10.1080/10618600.2021.1987255?scroll=top
devtools::install_github("https://github.com/gpage2990/drpm.git")
```{r}
library(drpm)
library(salso)
```

# Test drpm installation
```{r}
# preparation
source("include.R") # for having df_agri

sites = data.frame(
	longitude = unique(df_agri$Longitude)[1:10], 
	latitude = unique(df_agri$Latitude)[1:10])

# unique(df_agri[,c("Longitude","Latitude")])[1:10,] == sites[1:10,]
```

Again if there is some output it means that the installation went well :)

# simulated data
```{r}
# begin all in the same cluster
y01=matrix(data=rnorm(5,0,1),nrow = 5,ncol = 1)
y02=matrix(data=rnorm(5,0,1),nrow = 5,ncol = 1)
y0 = rbind(y01,y02)
# half in cluster 0, half in cluster 1
y11=matrix(data=rnorm(5,0,1),nrow = 5,ncol = 1)
y12=matrix(data=rnorm(5,10,1),nrow = 5,ncol = 1)
y1 = rbind(y11,y12)

# at time 2 they switch clusters
y21=matrix(data=rnorm(5,10,1),nrow = 5,ncol = 1)
y22=matrix(data=rnorm(5,0,1),nrow = 5,ncol = 1)
y2 = rbind(y21,y22)

# at time 3 they move in a new cluster
y31=matrix(data=rnorm(5,100,1),nrow = 5,ncol = 1)
y32=matrix(data=rnorm(5,100,1),nrow = 5,ncol = 1)
y3 = rbind(y31,y32)

# at time 4 they return to the clusters at 1
y41=matrix(data=rnorm(5,0,1),nrow = 5,ncol = 1)
y42=matrix(data=rnorm(5,10,1),nrow = 5,ncol = 1)
y4 = rbind(y41,y42)

y = cbind(y0,y1,y2,y3,y4)
as.data.frame(y)

cols = colora(size(y)[1],56,0)
for(i in 1:size(y)[1]){
	if(i==1){
		plot(y[i,],col=cols[i],ylim=extrema(y),type="l")
	}
	else{
		lines(y[i,],col=cols[i])
	}
}
```


```{r}
load('df_weekly.RData')
```


```{r}
stations = unique(df_weekly$IDStations)

y=data.frame()

for(st in stations){
  y_we_pm10=cbind(as.data.frame(st),t(df_weekly[which(df_weekly$IDStations==st),7]))
  y=rbind(y,y_we_pm10)
}
rownames(y)<-NULL
```




```{r}
yred=y[,2:54]
cols = colora(size(yred)[1],56,0)
for(i in 1:size(yred)[1]){
   if(i==1){
     plot(1:size(yred)[2],yred[i,],col=cols[i],ylim=extrema(yred),type='l',xlab='weeks',ylab='pm10')
 	  } 
	  else{
		  lines(1:size(yred)[2],yred[i,],col=cols[i])
	  }
}
```



```{r}
drpm1 <- drpm_fit(y[,2:54], 
         M=1,
         initial_partition = NULL,
         starting_alpha = 0.5,
         unit_specific_alpha = FALSE,
         time_specific_alpha = TRUE,
         alpha_0=FALSE,
         eta1_0=FALSE,
         phi1_0=FALSE,
         modelPriors=c(40,100^2,1,1,1,1),
         alphaPriors=rbind(c(1,1)),
         simpleModel = 0,
         theta_tau2 = c(0, 2),
         SpatialCohesion=4,
         cParms=c(0, 1, 2, 1),
         mh=c(0.5, 1, 0.1, 0.1, 0.1),
         verbose=TRUE,
         draws=1100,burn=100,thin=1)
names(drpm1)
```
```{r}
rho <- list()
for(t in 1:size(y[,2:54])[2]){
	rho[[t]] <- salso(t(drpm1$Si[t,,]),
					  #structure="clustering",
					  loss="binder")
}
rho
```

```{r}
names(drpm1)
```



